ingest: true
opentelemetry-demo:
  default:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: >-
          service.name=$(OTEL_SERVICE_NAME),
          k8s.namespace.name=$(OTEL_K8S_NAMESPACE),
          k8s.node.name=$(OTEL_K8S_NODE_NAME),
          k8s.pod.name=$(OTEL_K8S_POD_NAME),
          deployment.environment=opentelemetry-demo-agent
  observability:
    otelcol:
      enabled: false
datadog:
  datadog:
    apiKeyExistingSecret: "datadog-secrets"
    tags:
      - "env:otel-ingest"
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
