ingest: true
opentelemetry-demo:
  components:
    adService: &override
      envOverrides:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: 'http://{{ include "otel-demo.name" . }}-datadog:3317'
    redis: *override
    cartService: *override
    checkoutService: *override
    currencyService: *override
    emailService: *override
    featureflagService: *override
    ffsPostgres: *override
    frontend: *override
    frontendProxy: *override
    loadgenerator: *override
    paymentService: *override
    productCatalogService: *override
    recommendationService: *override
    shippingService: *override
    quoteService: *override
  observability:
    otelcol:
      enabled: false
datadog:
  datadog:
    apiKeyExistingSecret: "datadog-secrets"
    tags:
      - "env:otel-ingest"
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
            endpoint: "0.0.0.0:3317"
