opentelemetry-demo:
  default:
    envOverrides:
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: >-
          service.name=$(OTEL_SERVICE_NAME),
          k8s.namespace.name=$(OTEL_K8S_NAMESPACE),
          k8s.node.name=$(OTEL_K8S_NODE_NAME),
          k8s.pod.name=$(OTEL_K8S_POD_NAME),
          deployment.environment=opentelemetry-demo-collector
  opentelemetry-collector:
    extraEnvs:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: datadog-secrets
            key: api-key
            optional: false
    mode: "daemonset"
    config:
      exporters:
        datadog:
          metrics:
            histograms:
              mode: counters
              send_count_sum_metrics: true
          api:
            key: "$DD_API_KEY"
      processors:
        batch:
          send_batch_max_size: 1000
          send_batch_size: 100
          timeout: 10s
      service:
        pipelines:
          metrics: &pipeline
            processors:
              - memory_limiter
              - batch
            exporters:
              - datadog
          traces: *pipeline
          logs: *pipeline
