opentelemetry-demo:
  components:
    cartService:
      resources:
        limits:
          memory: 1Gi
    checkoutService:
      resources:
        limits:
          memory: 1Gi
    currencyService:
      resources:
        limits:
          memory: 1Gi
    featureflagService:
      resources:
        limits:
          memory: 1Gi
    frontend:
      resources:
        limits:
          memory: 1Gi
    frontendProxy:
      resources:
        limits:
          memory: 1Gi
    paymentService:
      resources:
        limits:
          memory: 1Gi
    productCatalogService:
      resources:
        limits:
          memory: 1Gi
    loadgenerator:
      resources:
        limits:
          memory: 1Gi
    quoteService:
      resources:
        limits:
          memory:
            1Gi
    adService:
      resources:
        limits:
          memory:
            1Gi
    emailService:
      resources:
        limits:
          memory:
            1Gi
  opentelemetry-collector:
    resources:
      limits:
        memory: 1Gi
        cpu: "1"
