{{- $ := set . "name" "otelcol" }}
{{- $otelconfig := include "otel-demo.otelcol.config" .}}

{{- if .Values.observability.otelcol.enabled -}}
{{- if not .Values.useOperator -}}
---
apiVersion: apps/v1
{{- if eq .Values.deployMode "deployment" }}
kind: Deployment
{{- end }}

{{- if eq .Values.deployMode "daemonset" }}
kind: DaemonSet
{{- end }}
metadata:
  name: {{ include "otel-demo.name" . }}-{{ .name }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.deployMode "deployment" }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        checksum/otel_config: {{ sha256sum $otelconfig | trunc 63 }}
        {{- include "otel-demo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "otel-demo.name" . }}
      containers:
      - image: dineshgurumurthydd/otelcol:{{ $.Values.image.otelcolversion }}
        imagePullPolicy: Always
        name: otel-col
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                key:  datadog_api_key
                name: {{ include "otel-demo.name" . }}-{{ .name }}-dd-secret
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 400Mi
        args:
          - "--config=/etc/config/otelcol-config.yml"
        ports:
         {{- if eq .Values.deployMode "daemonset" }}
          - containerPort: 4317
            hostPort: 4317
            protocol: TCP
          - containerPort: 4318
            hostPort: 4318
            protocol: TCP
          {{- end }}
         {{- if eq .Values.deployMode "deployment" }}
          - containerPort: 4317
            protocol: TCP
          - containerPort: 4318
            protocol: TCP
          {{- end }}
          - containerPort: 8888
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/config
            name: config
          - name: varlogpods
            mountPath: /var/log/pods
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      volumes:
        - configMap:
            name: {{ include "otel-demo.name" . }}-{{.name}}-config
          name: config
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
{{- end }}
{{- end }}
