{{- $ := set . "name" "otelcol" }}
{{- $otelconfig := include "otel-demo.otelcol.config" .}}

{{- if .Values.observability.otelcol.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-demo.name" . }}-{{ .name }}-config
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
data:
  otelcol-config.yml: |

    {{- $otelconfig | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otel-demo.name" . }}-{{ .name }}-dd-secret
data:
  datadog_api_key: {{ .Values.apiKey | quote | b64enc }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-demo.name" . }}-{{ .name }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otel-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        checksum/otel_config: {{ sha256sum $otelconfig | trunc 63 }}
        {{- include "otel-demo.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: init-config
        image: dibi/envsubst
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                key:  datadog_api_key
                name: {{ include "otel-demo.name" . }}-{{ .name }}-dd-secret
        volumeMounts:
        - name: config
          mountPath: /processed
        - name: otel-config-template
          mountPath: /workdir
      containers:
      - image: otel/opentelemetry-collector-contrib:{{ $.Values.image.otelcolversion }}
        name: otel-col
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 400Mi
        args:
          - "--config=/processed/otelcol-config.yml"
        ports:
          - containerPort: 4317
            protocol: TCP
          - containerPort: 4318
            protocol: TCP
          - containerPort: 8888
            protocol: TCP
        volumeMounts:
          - mountPath: /processed
            name: config
      volumes:
        - configMap:
            name: {{ include "otel-demo.name" . }}-{{.name}}-config
          name: otel-config-template
        - name: config
          emptyDir : {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-demo.name" . }}-{{ .name }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
spec:
  ports:
    - name: otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlphttp
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metric
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
      {{- include "otel-demo.selectorLabels" . | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "otel-demo.name" . }}-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - namespaces/status
  - nodes
  - nodes/spec
  - pods
  - pods/status
  - replicationcontrollers
  - replicationcontrollers/status
  - resourcequotas
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ include "otel-demo.name" . }}
    service: {{ include "otel-demo.name" . }}
  name: {{ include "otel-demo.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "otel-demo.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "otel-demo.name" . }}
  namespace: otel
roleRef:
  kind: ClusterRole
  name: {{ include "otel-demo.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
